version: "3.5"

services:
  postgres:
    container_name: postgressql_container
    image: postgres
    hostname: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/data/postgres
    volumes:
      - postgres:/var/lib/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbit:
    container_name: rabbit_container
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbit:/var/lib/data/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

volumes:
  postgres:
  rabbit:
